
version: '3.8'
services:
  product-service:
    build: ./java-microservices/product-service
    ports:
      - "8082:8080"
  user-service:
    build: ./java-microservices/user-service
    ports:
      - "8083:8080"
  order-service:
    build: ./java-microservices/order-service
    ports:
      - "8084:8080"
  bff:
    build: ./java-microservices/bff
    ports:
      - "8081:8081"
  ui:
    build: ./grocery-ui
    ports:
      - "80:80"
